### ISSUE TITLE
Multiple tab loads cause crash

### ISSUE THREAD

**Issue by ChristopherTrimboli** [webmixedreality/exokit-home#11]
error: 

SyntaxError: missing ) after argument list                                                                                  at _runJavascript (C:\exokit\core.js:3290:15)                                                                           at HTMLScriptElement.on.innerHTML (C:\exokit\core.js:2560:9)                                                            at HTMLScriptElement.emit (events.js:182:13)                                                                            at HTMLScriptElement.EventEmitter.emit (domain.js:442:20)                                                               at HTMLScriptElement._emit (C:\exokit\core.js:1398:40)                                                                  at HTMLScriptElement.set innerHTML [as innerHTML] (C:\exokit\core.js:2602:10)                                           at HTMLScriptElement.run (C:\exokit\core.js:2619:24)                                                                    at element.traverseAsync (C:\exokit\core.js:3261:16)                                                                    at HTMLBodyElement.traverseAsync (C:\exokit\core.js:2206:28)                                                            at process._tickCallback (internal/process/next_tick.js:68:7)                                                       Lifecycle library is not connected.                                                                                     Lifecycle library is not connected.

**Comment by avaer** [comment]
Theory: this looks like a file truncation of a loaded file.
